build-env51:
  tags:
  - docker,node
  only:
  - beta
  stage: build
  script:
  - echo "Installing dependencies..."
  - yarn install
  - echo "Building..."
  - rm -rf dist/ && yarn build
  - echo "Deploying..."
  - tar cf tw-web-env51.tar -C dist/ .
  - scp tw-web-env51.tar administrator@192.168.0.144:'c:\_temp\nginx-1.15.6\'
  - ssh administrator@192.168.0.144 'rd /s/q c:\_temp\nginx-1.15.6\telework_tenant1 & md c:\_temp\nginx-1.15.6\telework_tenant1'
  - ssh administrator@192.168.0.144 'cd c:\_temp\nginx-1.15.6\ && tar -xf tw-web-env51.tar -C telework_tenant1'